[features]
seeds = false
skip-lint = false
[programs.localnet]
lockdapp = "6i8FHTnCRhGC3XEH2FKwtKJ4zeEvtKPckcUUXLDz69ty"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/maryanpasichniak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
